//! Terraform providers, read from `.terraform.lock.hcl`.
//!
//! The only ecosystem here that needs no tool installed. The lock file
//! carries the resolved version in plain text, and the newest comes from
//! the registry over HTTP -- so unlike every other one, a missing
//! `terraform` binary cannot make this report nothing, which is the
//! failure mode #418 was entirely about.
//!
//! Parsed with a line scan rather than an HCL parser. The block this
//! reads is machine-generated by `terraform init` and its shape is
//! fixed:
//!
//!     provider "registry.terraform.io/hashicorp/archive" {
//!       version     = "2.8.0"
//!       constraints = ">= 2.4.0"
//!
//! A parser would be a dependency for two fields whose format Terraform
//! controls and does not vary.

use super::model::{Bump, Ecosystem, Outdated};
use std::path::Path;

/// How deep to look for lock files.
///
/// A Terraform repository is commonly many rooted modules rather than
/// one: on a real one, `modules/*/` and `environments/*/` each hold
/// their own lock. Matching only the root would find nothing at all
/// there.
const MAX_DEPTH: usize = 3;

/// Every provider pinned anywhere in this repository.
///
/// `latest` is left EQUAL to `current` and `bump` is `Unknown`: this
/// pass reports what is installed, and `registry::enrich` fills in what
/// is available. Reporting an unknown latest as an update would be the
/// confidently-wrong answer this module exists to avoid.
pub fn pinned(repo: &Path) -> Vec<Outdated> {
    let mut out = Vec::new();
    for lock in lock_files(repo) {
        let Ok(text) = std::fs::read_to_string(&lock) else {
            continue;
        };
        // The path RELATIVE to the repo, so a row says which module it
        // came from -- with many locks per repo, the bare filename would
        // be the same string a dozen times.
        let manifest = lock
            .strip_prefix(repo)
            .unwrap_or(&lock)
            .to_string_lossy()
            .to_string();
        for (name, version) in providers(&text) {
            out.push(Outdated {
                name,
                current: version.clone(),
                latest: version,
                bump: Bump::Unknown,
                ecosystem: Ecosystem::Terraform,
                manifest: manifest.clone(),
            });
        }
    }
    out
}

/// `(source, version)` for each provider block.
///
/// The source is the full registry address -- `registry.terraform.io/
/// hashicorp/archive` -- because that IS the lookup key, and shortening
/// it here would mean reconstructing it later.
fn providers(text: &str) -> Vec<(String, String)> {
    let mut out = Vec::new();
    let mut current: Option<String> = None;
    for line in text.lines() {
        let t = line.trim();
        if let Some(rest) = t.strip_prefix("provider ") {
            current = rest
                .trim()
                .trim_start_matches('"')
                .split('"')
                .next()
                .map(str::to_string)
                .filter(|s| !s.is_empty());
        } else if let Some(name) = current.clone() {
            if let Some(rest) = t.strip_prefix("version") {
                if let Some(v) = rest.split('"').nth(1) {
                    out.push((name, v.to_string()));
                    // One version per block; anything after it belongs
                    // to hashes until the next `provider`.
                    current = None;
                }
            }
        }
    }
    out
}

/// Lock files under `repo`, to `MAX_DEPTH`.
fn lock_files(repo: &Path) -> Vec<std::path::PathBuf> {
    const SKIP: &[&str] = &[".git", ".terraform", "node_modules", "target", ".worktrees"];
    let mut out = Vec::new();
    let mut stack = vec![(repo.to_path_buf(), 0usize)];
    while let Some((dir, depth)) = stack.pop() {
        let Ok(entries) = std::fs::read_dir(&dir) else {
            continue;
        };
        for e in entries.flatten() {
            let path = e.path();
            let name = e.file_name().to_string_lossy().to_string();
            if path.is_dir() {
                if depth < MAX_DEPTH && !SKIP.contains(&name.as_str()) {
                    stack.push((path, depth + 1));
                }
            } else if name == ".terraform.lock.hcl" {
                out.push(path);
            }
        }
    }
    out.sort();
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The REAL shape `terraform init` writes, including the hashes
    /// block that follows the version and must not be mistaken for one.
    const LOCK: &str = r#"
provider "registry.terraform.io/hashicorp/archive" {
  version     = "2.8.0"
  constraints = ">= 2.4.0"
  hashes = [
    "h1:WB6H5ksIZiyq1lQlD/PWeh+tn4FLsbSjVnRW3+4xe2Y=",
  ]
}

provider "registry.terraform.io/hashicorp/aws" {
  version     = "5.100.0"
  constraints = ">= 5.0.0"
}
"#;

    #[test]
    fn reads_each_provider_and_its_version() {
        let got = providers(LOCK);
        assert_eq!(
            got,
            vec![
                (
                    "registry.terraform.io/hashicorp/archive".into(),
                    "2.8.0".into()
                ),
                (
                    "registry.terraform.io/hashicorp/aws".into(),
                    "5.100.0".into()
                ),
            ]
        );
    }

    /// The FULL address, not a shortened name: it is the registry lookup
    /// key, and shortening it here means rebuilding it later.
    #[test]
    fn keeps_the_whole_registry_address() {
        let got = providers(LOCK);
        assert!(got[0].0.starts_with("registry.terraform.io/"));
    }

    /// A `constraints` line is not a version, and neither is a hash.
    #[test]
    fn does_not_mistake_other_lines_for_a_version() {
        assert_eq!(providers(LOCK).len(), 2, "exactly one version per block");
    }

    /// ONE version per block, even when a later line also starts with
    /// the word.
    ///
    /// Real lock files carry `version_constraints` and hash entries
    /// after the version, and without closing the block on the first
    /// match a second line would be read as another provider at a
    /// different version -- the same dependency reported twice, at odds
    /// with itself.
    #[test]
    fn a_second_version_line_in_one_block_is_ignored() {
        let lock = r#"
provider "registry.terraform.io/hashicorp/aws" {
  version     = "5.100.0"
  version_constraints = "9.9.9"
}
"#;
        let got = providers(lock);
        assert_eq!(got.len(), 1, "one provider, not two: {got:?}");
        assert_eq!(got[0].1, "5.100.0");
    }

    #[test]
    fn an_empty_or_unrelated_file_yields_nothing() {
        assert!(providers("").is_empty());
        assert!(providers("# just a comment\nfoo = 1\n").is_empty());
    }

    /// Every row reports Unknown until the registry says otherwise.
    /// Claiming `latest == current` means "up to date" would be the
    /// confidently-wrong answer.
    #[test]
    fn pinned_rows_start_uncompared() {
        let t = tempfile::TempDir::new().unwrap();
        std::fs::write(t.path().join(".terraform.lock.hcl"), LOCK).unwrap();
        let out = pinned(t.path());
        assert_eq!(out.len(), 2);
        for o in &out {
            assert_eq!(o.bump, Bump::Unknown);
            assert_eq!(o.latest, o.current);
        }
    }

    /// A real repo pins per module, so the row must say WHICH.
    #[test]
    fn finds_locks_in_nested_modules() {
        let t = tempfile::TempDir::new().unwrap();
        let deep = t.path().join("modules").join("data");
        std::fs::create_dir_all(&deep).unwrap();
        std::fs::write(deep.join(".terraform.lock.hcl"), LOCK).unwrap();
        let out = pinned(t.path());
        assert_eq!(out.len(), 2);
        assert!(
            out[0].manifest.contains("modules/data"),
            "the row must name its module: {}",
            out[0].manifest
        );
    }
}

/// Against a REAL Terraform repository. Ignored: it reads a path
/// outside this one.
///
/// `HEADSTATE_TF_REPO=/path cargo test -- --ignored real_tf --nocapture`
#[cfg(test)]
mod real {
    use super::*;

    #[test]
    #[ignore = "reads a real Terraform repository"]
    fn reports_the_providers_it_finds() {
        let Ok(repo) = std::env::var("HEADSTATE_TF_REPO") else {
            eprintln!("set HEADSTATE_TF_REPO");
            return;
        };
        let out = pinned(Path::new(&repo));
        eprintln!("providers found: {}", out.len());
        let mut seen: Vec<String> = out.iter().map(|o| o.name.clone()).collect();
        seen.sort();
        seen.dedup();
        eprintln!("distinct providers: {}", seen.len());
        for o in out.iter().take(4) {
            eprintln!("  {} {} <- {}", o.name, o.current, o.manifest);
        }
        assert!(
            !out.is_empty(),
            "a real Terraform repo must yield providers"
        );
    }
}
