#!/usr/bin/env python3
"""Every `@tauri-apps/*` package must match its Rust crate on major/minor.

Tauri refuses to bundle when an npm package and its paired crate disagree:

    Found version mismatched Tauri packages. Make sure the NPM package and
    Rust crate versions are on the same major/minor releases:
    tauri-plugin-updater (v2.10.1) : @tauri-apps/plugin-updater (v2.11.0)

That check lives inside `tauri build`, which runs in one CI job and in
`make build` -- not in `make lint` or `make test`. So the loop a person
runs before pushing cannot catch it, and the failure arrives from the
slowest job after everything else has gone green. Caught for real by
#552, where a `yarn up` of the updater plugin left its crate behind
(#555).

The drift is possible because BOTH sides are declared as ranges and the
CLI compares RESOLVED versions. `@tauri-apps/plugin-updater: ^2.10.1`
and `tauri-plugin-updater = "2"` are each free to move when their own
lockfile is regenerated, and the two lockfiles are regenerated by
different commands. Dependabot updates one ecosystem per pull request by
construction, so it produces exactly this mismatch by design.

This reads the same resolved versions the CLI would, from the lockfiles,
and answers the same question without building anything.

Deliberately parses the two lockfiles by line rather than importing a
TOML or YAML library: the lint runner has no third-party Python
packages, and a guard that needs its own install is a guard that gets
dropped -- the reasoning `check-workflow-shells.py` already follows.
Both formats are machine-written and the shapes read here (`name = "x"`
followed by `version = "y"` in Cargo.lock; a `"pkg@npm:range":` header
followed by `version: x` in yarn.lock) are stable and narrow.
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

# Which Cargo.lock pairs with which crates. The root package.json is
# shared: the desktop app and the phone app both take their JS from it,
# so a mismatch in either lockfile is a real mismatch.
LOCKS = ("src-tauri/Cargo.lock", "src-mobile/Cargo.lock")

# Crates driven entirely from Rust, with no npm half to drift against.
#
# Two kinds. The in-repo mobile plugins are path dependencies of our own
# making, and `tauri-plugin` is the plugin-authoring crate rather than a
# plugin. The rest are ordinary Tauri plugins we happen to call only
# from Rust: `notification`, `log` and `autostart` on the desktop,
# `barcode-scanner` and `stronghold` on the phone.
#
# The second kind is a judgement, not a fact about the crate: adding the
# npm half later is normal (the barcode scanner's JS package is expected
# when the phone's pairing screen lands). So an unpaired crate is
# reported as a note rather than a failure -- see `main`.
RUST_ONLY = {
    "tauri-plugin",
    "tauri-plugin-headstate-keys",
    "tauri-plugin-headstate-refresh",
    "tauri-plugin-autostart",
    "tauri-plugin-barcode-scanner",
    "tauri-plugin-log",
    "tauri-plugin-notification",
    "tauri-plugin-stronghold",
}


def crate_for(package: str) -> str:
    """The Rust crate paired with an `@tauri-apps/*` package.

    Derived rather than listed, so a plugin added tomorrow is covered
    without editing this file. `@tauri-apps/plugin-x` pairs with
    `tauri-plugin-x`; `@tauri-apps/api` is the JS half of the `tauri`
    crate itself.
    """
    name = package.removeprefix("@tauri-apps/")
    if name == "api":
        return "tauri"
    if name.startswith("plugin-"):
        return "tauri-" + name
    return ""


def npm_packages(package_json: str) -> set[str]:
    """Every `@tauri-apps/*` package named in package.json.

    The CLI itself (`@tauri-apps/cli`) is excluded: it is a build tool
    with no crate in our tree, and Tauri does not pair it.
    """
    found = set(re.findall(r'"(@tauri-apps/[^"]+)"\s*:', package_json))
    return {p for p in found if p != "@tauri-apps/cli"}


def yarn_resolved(lock: str) -> dict[str, str]:
    """Resolved version per `@tauri-apps/*` package from yarn.lock.

    An entry is a header line naming one or more descriptors, then an
    indented `version:`. A package can appear more than once at
    different versions; every one of them is recorded, because any of
    them could be the mismatch.
    """
    out: dict[str, set[str]] = {}
    names: list[str] = []
    for line in lock.splitlines():
        if line and not line[0].isspace() and line.rstrip().endswith(":"):
            names = re.findall(r"(@tauri-apps/[^@\"]+)@npm:", line)
            continue
        if names:
            m = re.match(r'\s+version:\s*"?([^"\s]+)"?', line)
            if m:
                for n in names:
                    out.setdefault(n, set()).add(m.group(1))
                names = []
    # More than one resolved version of the same package is itself a
    # problem the CLI would trip over; report them all rather than
    # picking one.
    return {k: ", ".join(sorted(v)) for k, v in out.items()}


def cargo_resolved(lock: str) -> dict[str, str]:
    """Resolved version per crate from a Cargo.lock."""
    out: dict[str, str] = {}
    name = None
    for line in lock.splitlines():
        m = re.match(r'^name = "([^"]+)"', line)
        if m:
            name = m.group(1)
            continue
        m = re.match(r'^version = "([^"]+)"', line)
        if m and name:
            out[name] = m.group(1)
            name = None
    return out


def major_minor(version: str) -> tuple[str, str]:
    parts = version.split(".")
    return (parts[0], parts[1] if len(parts) > 1 else "0")


def main() -> int:
    package_json = (ROOT / "package.json").read_text()
    yarn = yarn_resolved((ROOT / "yarn.lock").read_text())
    packages = npm_packages(package_json)

    problems: list[str] = []

    for package in sorted(packages):
        crate = crate_for(package)
        if not crate:
            # A `@tauri-apps/*` package whose crate we cannot name is
            # not silently skipped: either the mapping needs widening or
            # the package does not belong here, and both want a human.
            problems.append(
                f"{package} has no known Rust crate. Add it to crate_for() "
                f"in {pathlib.Path(__file__).name} or to the exclusions."
            )
            continue
        if package not in yarn:
            problems.append(f"{package} is in package.json but not resolved in yarn.lock")
            continue

        js = yarn[package]
        for lock_path in LOCKS:
            crates = cargo_resolved((ROOT / lock_path).read_text())
            if crate not in crates:
                continue
            rust = crates[crate]
            if major_minor(js) != major_minor(rust):
                problems.append(
                    f"{lock_path}: {crate} (v{rust}) : {package} (v{js})\n"
                    f"    Tauri requires the same major/minor. Fix with:\n"
                    f"      cd {pathlib.Path(lock_path).parent} && cargo update -p {crate}\n"
                    f"    or move the npm side to match."
                )

    # The other direction: a Tauri plugin crate whose npm half is absent.
    #
    # A NOTE, not a failure. Calling a plugin only from Rust is a valid
    # choice and several here do exactly that, so failing would mean
    # editing this script every time one is added -- the kind of friction
    # that gets a guard deleted. But a plugin that is meant to be driven
    # from JS and is missing its package fails at runtime rather than at
    # build time, which is worth a line on the way past.
    notes: list[str] = []
    for lock_path in LOCKS:
        for crate in sorted(cargo_resolved((ROOT / lock_path).read_text())):
            if crate in RUST_ONLY or not crate.startswith("tauri-plugin-"):
                continue
            package = "@tauri-apps/" + crate.removeprefix("tauri-")
            if package not in packages:
                notes.append(
                    f"{lock_path}: {crate} has no {package} in package.json. "
                    f"Fine if it is driven only from Rust; add it to RUST_ONLY "
                    f"in {pathlib.Path(__file__).name} to silence this."
                )

    if problems:
        print("tauri version check: mismatched packages\n", file=sys.stderr)
        for p in problems:
            print(f"  {p}", file=sys.stderr)
        print(
            "\nThese must agree before `tauri build` will bundle. See #555.",
            file=sys.stderr,
        )
        return 1

    for n in notes:
        print(f"note: {n}")
    print(f"tauri version check: clean ({len(packages)} paired packages)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
