//! The stats layer's GraphQL documents. Reads only, like `query.rs` one
//! level up, and for the same reason: this file stays auditable as pure
//! search and connection lookups.
//!
//! Two shapes, and the difference between them is the whole routing
//! decision of #824 item 5:
//!
//! - [`probe_query`] and [`slice_detail_query`] use `search`, which is
//!   capped at 1,000 retrievable results and is the only way to ask a
//!   question that spans repositories.
//! - [`repo_connection_query`] uses `repository.pullRequests`, a
//!   connection with no such cap, which is both exact and cheaper for a
//!   single-repo scope.

use crate::github::stats::scope::StatsQuery;

/// Searches per aliased document.
///
/// # This is a LATENCY budget, and the ceiling is a DEADLINE, not an
/// alias count
///
/// `query.rs:226-231` records the ceiling as "~44 aliases: 28-36 succeed
/// 5/5, 44-46 fail intermittently, 60 fails outright", and #823 measured
/// a 502 at 60. I re-measured on 2026-09-11 and the alias count is not
/// what the server is refusing. Every figure below is mine, `gh api
/// graphql` against `org:FNX-Labs`, three runs each:
///
/// | Document shape                     | Aliases | Wall clock     | Result  |
/// |------------------------------------|---------|----------------|---------|
/// | `search { issueCount }`            | 10      | 1.78-1.81s     | ok      |
/// | `search { issueCount }`            | 20      | 2.79-3.21s     | ok      |
/// | `search { issueCount }`            | 36      | 4.40-4.74s     | ok      |
/// | `search { issueCount }`            | 60      | 7.54-7.68s     | ok      |
/// | `search { issueCount }`            | 80      | 8.95-10.48s    | ok      |
/// | `search { issueCount }`            | 100     | 10.97-10.99s   | **502** |
/// | `search(first: 100) { nodes {..} }`| 12      | 3.69-5.21s     | ok      |
/// | `search(first: 100) { nodes {..} }`| 24      | 6.30-7.15s     | ok      |
/// | `search(first: 100) { nodes {..} }`| 36      | 9.22-10.84s    | ok      |
/// | `search(first: 100) { nodes {..} }`| 48      | 10.94s         | **502** |
///
/// The node-heavy document fails at 48 aliases where the count-only one
/// succeeds at 80, so the alias count cannot be the limit. What every
/// failure has in common is the CLOCK: all five 502s landed at
/// 10.94-10.99s, and nothing that answered inside ~10.8s ever failed.
/// It is a server-side deadline of roughly 11 seconds, and alias count
/// matters only because serial evaluation is what drives elapsed time
/// toward it. (The nginx 502 body confirms a gateway timeout rather than
/// a GraphQL objection -- which is also why it arrives as
/// `ClientError::NotJson`, see `client.rs:94-120`.)
///
/// # And the ranges above were SPARSE
///
/// Every row above probes ranges holding a handful of PRs each. Against
/// DENSE ranges -- three month-slices of `org:FNX-Labs` holding 416 / 581
/// / 79 merged PRs -- the document generated by [`slice_detail_query`]
/// itself measured:
///
/// | Aliases x page | Wall clock       | Result      |
/// |----------------|------------------|-------------|
/// | 3 x 100        | 11.0s, then 8.1s | **502**, ok |
/// | 3 x 50         | 3.42-3.68s       | ok 2/2      |
/// | 1 x 100        | 0.52s            | ok 2/2      |
///
/// THREE aliases straddle the deadline when the pages are actually full.
/// So the real driver is the number of NODES MATERIALISED, and alias
/// count is only a proxy for it -- which is why the page size, not the
/// alias count, is the first thing `fetch::degrade` sheds, and why
/// `fetch::SLICE_PAGE_FULL` defaults to 50 rather than 100.
///
/// This REINFORCES the epic's correction rather than undoing it: chunk
/// small and parallelise. It changes why, twice. A chunk size picked as a
/// fraction of an alias ceiling would be safe only for the document shape
/// AND the data density it was measured on -- 48 aliases looked like
/// ample headroom under a 60-alias ceiling, and 36 looked safe until the
/// ranges held real data.
///
/// 10 is sized against the deadline at the default 50-node page: 3
/// aliases x 50 measured 3.42-3.68s on the densest slices in this
/// account, so 10 has room even if every slice is full. It also matches
/// `query::HISTORY_CHUNK_DAYS`'s effective 10 aliases per chunk, which is
/// already measured-and-shipped at 2.36-2.8s, and keeps the existing
/// `<= 40` CI assertion (`query.rs:647-665`) comfortably satisfied.
pub const ALIAS_CHUNK: usize = 10;

/// The upper bound any chunk must respect, asserted in CI.
///
/// Expressed as an alias count because that is what a reviewer editing a
/// chunk size can check, but derived from the deadline above: 40 aliases
/// is ~5s on the count-only shape and ~11s on the node-heavy one, so it
/// is the point past which the expensive document stops being safe. The
/// existing test at `query.rs:647-665` asserts the same number for the
/// history chunks; keeping one figure means the two cannot drift into
/// disagreeing about what "safe" is.
pub const ALIAS_CEILING: usize = 40;

/// One date range to probe or fetch.
///
/// `from` and `to` are inclusive `YYYY-MM-DD`, GitHub's own range
/// grammar and the format `query::period_ranges` already produces.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Slice {
    pub from: String,
    pub to: String,
}

impl Slice {
    pub fn new(from: impl Into<String>, to: impl Into<String>) -> Self {
        Self {
            from: from.into(),
            to: to.into(),
        }
    }
}

/// Alias for the slice at `index`. `s0`, `s1`, ...
///
/// Indices are ABSOLUTE across a whole load, never per chunk, for the
/// reason `query.rs:667-678` records: chunks complete out of order and
/// merge into one map, so a per-chunk index would have chunk two's `s0`
/// silently overwrite chunk one's.
pub fn slice_alias(index: usize) -> String {
    format!("s{index}")
}

/// `issueCount` for each slice, and nothing else.
///
/// This is the probe that drives the slicing in `slice.rs`. No `nodes`,
/// so none of the per-PR fields are resolved at all -- the same
/// reasoning `query::COUNT_QUERY` gives for existing.
///
/// MEASURED 2026-09-11: cost 1 for the whole document at 36, 60 and 80
/// aliases. `rateLimit` is selected so that cost is READ rather than
/// assumed, which is #824 item 1 -- and so the assumption above is
/// checked at runtime on every probe rather than only on the day I
/// measured it.
pub fn probe_query(q: &StatsQuery, slices: &[Slice], first_index: usize) -> String {
    let mut doc = String::from("query {\n  rateLimit { cost remaining resetAt }\n");
    for (i, s) in slices.iter().enumerate() {
        let alias = slice_alias(first_index + i);
        let search = q.search_query(&s.from, &s.to);
        doc.push_str(&format!(
            "  {alias}: search(query: {}, type: ISSUE) {{ issueCount }}\n",
            graphql_string(&search)
        ));
    }
    doc.push_str("}\n");
    doc
}

/// The per-PR detail a leaderboard needs, for each slice.
///
/// `issueCount` rides along on every alias so a slice that is ALREADY
/// over the 1,000 cap is detectable from the same response that returned
/// its nodes -- the count is the true total and the node list is what was
/// retrievable. Without it, a truncated slice and a complete one look
/// identical, which is the silent-truncation shape #802 and #790 both
/// shipped.
///
/// `additions`, `deletions` and `changedFiles` are SCALARS and cost
/// nothing extra. MEASURED 2026-09-11: 12 aliases x 100 nodes carrying
/// all three plus `author { login }` cost **1 point** in 3.69-5.21s.
///
/// `reviews { totalCount }` is here as of #826, and it is free -- which is
/// NOT what #823 and #827 believed. Both recorded it as "a connection,
/// priced per search". Re-measured live (`gh api graphql`, 2026-09-11,
/// `org:FNX-Labs`, this document): `reviews { totalCount }` costs 1 point
/// at 3, 6 and 15 searches, exactly tracking the scalars-only control,
/// while `reviews(first: 1) { totalCount }` costs **2** from 6 searches
/// up. `labels` behaves identically both ways.
///
/// So what GitHub prices is a connection that PAGES -- one carrying a
/// `first:` argument -- not one read for `totalCount`. That reconciles
/// with `poll.rs:1503-1580` rather than contradicting it: every connection
/// on that test's cost list is paged. The rule for this document is
/// therefore "no `first:` inside the node selection", and
/// `the_detail_slice_carries_only_unpriced_fields` is what enforces it.
/// `board.rs`'s module docs carry the full measurement table.
///
/// The field is a review count RECEIVED, since it hangs off a PR the
/// subject authored. A board of reviews GIVEN would need
/// `reviewed-by:<login>`, which is one search per person -- a different
/// and much more expensive question, and the reason `AuthorRow`'s field is
/// named `reviews_received`.
///
/// `number`, `title`, `url` and `repository { nameWithOwner }` carry the
/// pull request's IDENTITY, which the outlier lists need: #826 keeps
/// `Outliers`, and its whole point is that "every figure on this page was a
/// scalar: it could report that something took four days or ran to ten
/// thousand lines and then not say WHICH pull request that was". MEASURED
/// 2026-09-11 on the same dense day-slices: adding all four leaves the
/// document at **cost 1** and is, if anything, faster (5 aliases x 50:
/// 3.81-4.77s with identity against 3.93-5.90s without, 3 runs each -- the
/// difference is noise, and the point is that there is no penalty).
/// `repository` is an OBJECT rather than a connection, which is why; it was
/// measured rather than assumed because that is this layer's rule.
pub fn slice_detail_query(
    q: &StatsQuery,
    slices: &[Slice],
    first_index: usize,
    first: u32,
) -> String {
    let mut doc = String::from("query {\n  rateLimit { cost remaining resetAt }\n");
    for (i, s) in slices.iter().enumerate() {
        let alias = slice_alias(first_index + i);
        let search = q.search_query(&s.from, &s.to);
        doc.push_str(&format!(
            // The alias's own closing brace is INDENTED and kept off a
            // line of its own. A bare "}" on its own line is
            // indistinguishable from the document's top-level closing
            // brace, which is what `documents_are_balanced` checks for --
            // and that check is worth keeping sharp, because an extra or
            // missing top-level brace is a whole-document syntax error
            // that no mapper test would catch.
            "  {alias}: search(query: {}, type: ISSUE, first: {first}) {{\n\
             \x20   issueCount\n\
             \x20   nodes {{ ... on PullRequest {{ number title url repository {{ nameWithOwner }} author {{ login }} createdAt mergedAt additions deletions changedFiles reviews {{ totalCount }} }} }} }}\n",
            graphql_string(&search)
        ));
    }
    doc.push_str("}\n");
    doc
}

/// Alias for the reviewer at `index`. `v0`, `v1`, ...
///
/// `v` for reviewer, because `r` is taken by nothing here yet but `s` is
/// already the slice prefix and a one-letter collision between two alias
/// families that merge into ONE map is the `slice_alias` failure mode
/// exactly: chunk two's `r0` silently overwriting chunk one's. Indices are
/// ABSOLUTE across a whole load for the same reason, `query.rs:667-678`'s
/// rule.
pub fn reviewer_alias(index: usize) -> String {
    format!("v{index}")
}

/// Reviews GIVEN: one `reviewed-by:<login>` count per person (#826).
///
/// # Why this cannot be a field on the detail document
///
/// `slice_detail_query` above reads `reviews { totalCount }` off each PR
/// node, which counts reviews that pull request RECEIVED -- and since the
/// node is attributed to its AUTHOR, the board built from it ranks people by
/// how much review their own work attracted. A node says how many reviews it
/// has; it never says who wrote them. So reviews given are not a cheaper
/// projection of the same document, they are a different search, and #829
/// was right to ship the correctly-titled "most-reviewed" board rather than
/// print it under "top reviewers".
///
/// MEASURED, and the two boards genuinely name DIFFERENT people on this
/// account's own data (live API, `gh api graphql`, 2026-09-11): a
/// `reviewed-by:<viewer> org:<org> merged:2026-01-01..2026-09-10` search
/// returned two pull requests, both **authored by somebody else** and each
/// carrying `reviews { totalCount } == 1`. So those same two pull requests
/// credit the AUTHOR on the received board and the REVIEWER on the given one.
/// No single chart could have been both, which is what made the mislabelling
/// a correctness bug rather than a wording one.
///
/// # Cost: one point. The expense is LATENCY
///
/// One search per login, all aliased into one document. MEASURED live
/// 2026-09-11 against `org:FNX-Labs`, 3 runs per cell:
///
/// | Reviewer aliases | Cost | Wall clock |
/// |---|---|---|
/// | 4 (this account's real org size) | **1** | 0.84-1.04s |
/// | 10 | **1** | 1.26-1.50s |
/// | 36 | **1** | 3.62-4.15s |
///
/// Free on rate limit at every size and linear in latency -- which
/// reproduces #823's history-document figures (10 aliases 2.36s, 36 7.67s)
/// on the same count-only shape. This document is comfortably FASTER than
/// those because each alias here is a single search rather than two.
///
/// It is chunked at [`ALIAS_CHUNK`] rather than at
/// `board::BOARD_ALIAS_CHUNK`, and the asymmetry is the measured one: this
/// document materialises NO nodes, so the ~11s deadline that governs the
/// detail document does not bind it the same way. `board.rs`'s table is the
/// evidence -- 10 node-bearing aliases at a 50-node page failed 0 of 3 at
/// 10.6s, where 36 count-only aliases here answer in 3.6-4.2s. Nodes drive
/// the deadline, so the page size is what `fetch::degrade` sheds first and
/// `fetch::SLICE_PAGE_FULL` stays at 50; a document with no page cannot be
/// made safer by shrinking one.
///
/// # `issueCount` is read UNPAGED, and must stay that way
///
/// No `first:` argument anywhere in this document. #826's measurement is
/// that GitHub prices the `first:` ARGUMENT rather than the connection --
/// `reviews { totalCount }` costs 1 at 15 searches while
/// `reviews(first: 1) { totalCount }` costs 2 from 6 searches up (the table
/// is in `board.rs`'s module docs). #823 carries a partial disagreement
/// about whether the paged form is ACTIVELY more expensive; both
/// measurements agree the unpaged form is free, so this takes the cheap path
/// neither disputes. Adding `first:` here would buy nothing -- a count needs
/// no page -- and could cost a point per search.
///
/// # One window, not one slice per day
///
/// The 1,000-result cap that forces `slice.rs` to subdivide applies to
/// RETRIEVING results, not to counting them: `issueCount` is exact at any
/// size (`slice.rs`'s `SUBDIVIDE_AT` doc records that the cap is what makes
/// a count exact below 800 and a NODE LIST short above it). This document
/// retrieves nothing, so one alias covers the whole window and the
/// subdivision machinery is not needed -- and must not be used, because
/// summing per-day counts would DOUBLE-COUNT a reviewer who reviewed two
/// pull requests merged on the same day into the same number either way but
/// would silently overcount across slices if a PR's merge date ever
/// straddled two ranges. One range, one number, no arithmetic.
///
/// A reviewer with no reviews in the window comes back as `0` from GitHub
/// rather than as a missing alias, and the caller must keep that distinct
/// from an alias that FAILED -- `Reviewers::unmeasured` is where that
/// distinction lives.
pub fn reviewer_query(
    q: &StatsQuery,
    logins: &[String],
    window: &Slice,
    first_index: usize,
) -> String {
    let mut doc = String::from("query {\n  rateLimit { cost remaining resetAt }\n");
    for (i, login) in logins.iter().enumerate() {
        let alias = reviewer_alias(first_index + i);
        // Built by replacing the AUTHOR qualifier with a reviewer one, so
        // the state, scope and date qualifiers come from the one builder in
        // `scope.rs` rather than being reassembled here -- which that
        // module's docs forbid, because a subject spelled differently
        // between two aliases produces a total that counts nothing.
        //
        // `StatsQuery::reviewed_by` is what performs the swap, and it
        // asserts the author qualifier is absent rather than emitting both:
        // `author:X reviewed-by:Y` is a legal search that means "X's PRs
        // that Y reviewed", which is a third question and not this one.
        let search = q.reviewed_by(login, &window.from, &window.to);
        doc.push_str(&format!(
            "  {alias}: search(query: {}, type: ISSUE) {{ issueCount }}\n",
            graphql_string(&search)
        ));
    }
    doc.push_str("}\n");
    doc
}

/// A single repository's pull requests, through the CONNECTION.
///
/// The uncapped path, and the reason `Scope::needs_search` exists.
/// VERIFIED live 2026-09-11: `pktstorm/headstate` reports 337 merged
/// pull requests at cost 1, with no 1,000-result ceiling anywhere in the
/// connection -- where the same question asked through `search` on a
/// busy scope silently stops at 1,000 (`is:pr org:FNX-Labs` reports
/// 1,822 and offset 1000 returns `[]`).
///
/// `totalCount` is the connection's own exact total, so a caller can say
/// how much of it this page holds. Date filtering is NOT available on
/// this connection -- it takes `states`, `orderBy` and a cursor, but no
/// date range -- so the caller filters `createdAt`/`mergedAt` itself
/// after ordering by update time. That is stated here because it is the
/// one place the connection is WEAKER than search, and a reader comparing
/// the two needs to know the cost is a client-side filter rather than a
/// missing feature.
pub const REPO_CONNECTION_QUERY: &str = r#"
query($owner: String!, $name: String!, $first: Int!, $after: String) {
  rateLimit { cost remaining resetAt }
  repository(owner: $owner, name: $name) {
    pullRequests(first: $first, after: $after, states: MERGED, orderBy: { field: UPDATED_AT, direction: DESC }) {
      totalCount
      pageInfo { hasNextPage endCursor }
      nodes {
        number
        author { login }
        createdAt
        mergedAt
        additions
        deletions
        changedFiles
      }
    }
  }
}"#;

/// Merged and opened counts for each day in `days`, for one scope.
///
/// The scoped counterpart to `query::history_query_range`, which is
/// hardcoded `author:@me` and therefore cannot draw a chart for an
/// organisation or a colleague -- the one thing #823's second audience
/// needs. Two aliases per day, `m<i>` and `o<i>`, because a PR opened in
/// July and merged in August belongs to July's opened count and August's
/// merged count; `Measure`'s own doc comment records why those cannot share
/// an alias.
///
/// COUNT-ONLY, which is what makes it affordable. No `nodes`, so no
/// per-PR field is resolved at all and the deadline that governs the detail
/// document does not apply the same way: MEASURED 2026-09-11, 10 count-only
/// aliases over dense `org:FNX-Labs` day-slices answered in 1.4-1.5s where
/// the same 10 aliases carrying 50 nodes each straddled ~11s and failed.
/// So this document is chunked at the full [`ALIAS_CHUNK`], while
/// `board::BOARD_ALIAS_CHUNK` is half it -- two numbers because they size
/// two documents that measure seven times apart.
///
/// Alias indices are ABSOLUTE across the whole series for
/// `query.rs:667-678`'s reason: chunks complete out of order and merge into
/// one map, so a per-chunk index would have chunk two's `m0` overwrite
/// chunk one's.
pub fn series_query(q: &StatsQuery, days: &[String], first_index: usize) -> String {
    let mut doc = String::from("query {\n  rateLimit { cost remaining resetAt }\n");
    for (i, d) in days.iter().enumerate() {
        let n = first_index + i;
        // A fresh query per measure rather than one with the date swapped:
        // `StatsQuery` owns the qualifier order and the subject, and
        // rebuilding the string here is exactly the per-call-site
        // assembly `scope.rs`'s module docs forbid.
        let merged = q
            .with_measure(super::scope::Measure::Merged)
            .search_query(d, d);
        let opened = q
            .with_measure(super::scope::Measure::Opened)
            .search_query(d, d);
        doc.push_str(&format!(
            "  m{n}: search(query: {}, type: ISSUE) {{ issueCount }}\n",
            graphql_string(&merged)
        ));
        doc.push_str(&format!(
            "  o{n}: search(query: {}, type: ISSUE) {{ issueCount }}\n",
            graphql_string(&opened)
        ));
    }
    doc.push_str("}\n");
    doc
}

/// Aliases for the merged and opened counts of day `index`.
///
/// One function for both, so the two spellings cannot drift apart between
/// the document that writes them and the mapper that reads them -- the
/// failure `slice_alias` exists to prevent for the detail document.
pub fn day_aliases(index: usize) -> (String, String) {
    (format!("m{index}"), format!("o{index}"))
}

/// A Rust string as a GraphQL string literal.
///
/// The searches here are built from logins and repository names, which
/// GitHub allows to contain `-`, `.` and `_` but not a quote -- so this
/// cannot currently be reached by a hostile value. It escapes anyway,
/// because the subject is a parameter now (#824 item 7) and the next
/// caller to add is a sidebar (#825) handing over whatever GitHub
/// returned. An injected `"` would not be a security hole so much as a
/// query that fails in a way nobody could read; either way the fix
/// belongs in the one function that builds the literal, not in every
/// caller remembering.
fn graphql_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::github::stats::scope::{Measure, Scope, StatsQuery, Subject};

    fn q() -> StatsQuery {
        StatsQuery::new(
            Some(Subject::Login("octocat".into())),
            Scope::Org("FNX-Labs".into()),
            Measure::Merged,
        )
    }

    fn slices(n: usize) -> Vec<Slice> {
        (0..n)
            .map(|i| {
                Slice::new(
                    format!("2026-0{}-01", i % 9 + 1),
                    format!("2026-0{}-28", i % 9 + 1),
                )
            })
            .collect()
    }

    /// The chunk size must stay under the ceiling the history chunks
    /// already enforce (`query.rs:647-665` asserts `<= 40`), and this
    /// layer's documents are the EXPENSIVE shape -- 48 node-heavy
    /// aliases 502'd at 10.94s in my measurements, where 80 count-only
    /// aliases succeeded. A chunk sized against the cheap shape is not
    /// safe for this one.
    #[test]
    fn a_chunk_stays_well_under_the_deadline() {
        // `const` blocks: both are compile-time constants, so these fail
        // the BUILD rather than a test run.
        const {
            assert!(ALIAS_CHUNK <= ALIAS_CEILING, "chunk exceeds the ceiling");
            // Measured: 36 node-heavy aliases took 9.22-10.84s against a
            // ~11s deadline, so the ceiling cannot be raised past 40
            // without re-measuring the expensive document.
            assert!(ALIAS_CEILING <= 40, "re-measure before raising the ceiling");
        }
        let doc = probe_query(&q(), &slices(ALIAS_CHUNK), 0);
        assert_eq!(doc.matches("search(").count(), ALIAS_CHUNK);
        assert!(doc.matches("search(").count() <= ALIAS_CEILING);
    }

    /// The same ceiling the history chunks use, so the two cannot drift
    /// into disagreeing about what "safe" means.
    #[test]
    fn the_ceiling_matches_the_history_chunk_assertion() {
        let src = include_str!("../query.rs");
        assert!(
            src.contains("count() <= 40"),
            "query.rs no longer asserts a 40-alias ceiling; ALIAS_CEILING must move with it"
        );
    }

    /// Every document in this file, so a new one cannot be added without
    /// reaching the guards below.
    ///
    /// `series_query` was missing from BOTH `every_document_meters_itself`
    /// and `documents_are_balanced` (#847's table), which is what this
    /// function is for: the two guards now iterate one list, so a document
    /// added to this module is either in that list or conspicuously absent
    /// from it. Named rather than derived -- a `pub fn` in this file is not
    /// necessarily a document builder (`slice_alias` and `day_aliases` are
    /// not), so scanning for `pub fn` would assert against the wrong things.
    fn every_document() -> Vec<(&'static str, String)> {
        let window = Slice::new("2026-08-12", "2026-09-10");
        let logins = ["a".to_string(), "b".to_string(), "c".to_string()];
        let days = ["2026-09-08".to_string(), "2026-09-09".to_string()];
        vec![
            ("probe_query", probe_query(&q(), &slices(3), 0)),
            (
                "slice_detail_query",
                slice_detail_query(&q(), &slices(3), 0, 100),
            ),
            ("series_query", series_query(&q(), &days, 0)),
            ("reviewer_query", reviewer_query(&q(), &logins, &window, 0)),
            ("REPO_CONNECTION_QUERY", REPO_CONNECTION_QUERY.to_string()),
        ]
    }

    /// Every document in this file selects `rateLimit`, so its cost is
    /// readable. A query that forgot it would have its spend counted as
    /// `unmetered` rather than guessed -- honest, but it would make the
    /// reported total a floor for no reason.
    ///
    /// Iterates [`every_document`] rather than listing three by hand, which
    /// is how `series_query` came to be absent from it (#847).
    #[test]
    fn every_document_meters_itself() {
        for (name, doc) in every_document() {
            assert!(
                doc.contains("rateLimit { cost remaining resetAt }"),
                "{name} does not select rateLimit; its cost cannot be read"
            );
        }
    }

    /// Every field the board's mapper READS, taken from the mapper's own
    /// source -- the same derivation `query.rs`'s `fields_read_by` performs,
    /// applied to the document on this side of the module boundary.
    ///
    /// `Board::from_alias_map` (`board.rs:459`) indexes `serde_json::Value`
    /// by string literal, so every field it reads appears in its body as
    /// `["name"]`. Deriving the list means a field added to the mapper
    /// demands its place in the document on the next `cargo test`, with
    /// nothing for a reviewer to remember -- which is the failure mode
    /// #842's poll guard and #844's metering guard both document.
    ///
    /// This SUBSUMES `board.rs:1521`'s hand-written
    /// `the_detail_document_carries_pull_request_identity` for the four
    /// identity fields and extends it to every other field the mapper reads.
    /// That test stays: it also asserts the NEGATIVE (`!contains
    /// "repository("`), which a read-set derivation cannot express, and its
    /// four names are the ones whose absence is silent rather than zero.
    #[test]
    fn the_detail_document_carries_every_field_the_board_reads() {
        let src = include_str!("board.rs");
        let anchor = "pub fn from_alias_map(";
        let from = src
            .find(anchor)
            .expect("from_alias_map not found in board.rs");
        // To the end of the impl block's next method, so only this mapper's
        // reads are collected. `query.rs:796-816` scopes the same way and
        // for the same reason: a test that reads the wrong region reports a
        // defect at a location that does not have one.
        let body = &src[from..];
        let end = ["\n    fn ", "\n    pub fn ", "\n#[cfg(test)]"]
            .iter()
            .filter_map(|m| body[1..].find(m).map(|i| i + 1))
            .min()
            .unwrap_or(body.len());
        let body = &body[..end];

        let doc = slice_detail_query(&q(), &slices(1), 0, 50);
        let mut found = 0usize;
        let mut rest = body;
        while let Some(i) = rest.find("[\"") {
            rest = &rest[i + 2..];
            let Some(j) = rest.find('"') else { break };
            let name = &rest[..j];
            if rest[j..].starts_with("\"]")
                && !name.is_empty()
                && name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')
            {
                found += 1;
                assert!(
                    doc.contains(name),
                    "Board::from_alias_map reads `{name}` and slice_detail_query does \
                     not select it; the mapper defaults it, so a missing field renders \
                     as a measurement rather than as a gap"
                );
            }
            rest = &rest[j..];
        }
        assert!(
            found >= 10,
            "only {found} field reads found in from_alias_map -- the scan is broken, \
             not the document"
        );
    }

    /// The series document carries what its mapper reads, which is one
    /// field and two alias families.
    ///
    /// `series_inner` (`fetch.rs:816`) reads `v[&m]["issueCount"]` through
    /// an alias held in a LOCAL, so the derivation above cannot see it:
    /// only the field name is a literal. Asserted by hand for that reason,
    /// and the aliases are asserted through `day_aliases` so the document
    /// and the reader cannot spell them differently -- the failure
    /// `slice_alias`'s doc describes.
    #[test]
    fn the_series_document_carries_what_its_reader_reads() {
        let days = ["2026-09-08".to_string(), "2026-09-09".to_string()];
        let doc = series_query(&q(), &days, 7);
        for i in 0..days.len() {
            let (m, o) = day_aliases(7 + i);
            assert!(
                doc.contains(&format!("{m}: search")),
                "series_inner reads the `{m}` alias; a document that does not \
                 build it leaves that day unmeasured"
            );
            assert!(doc.contains(&format!("{o}: search")));
        }
        assert!(
            doc.contains("issueCount"),
            "a count document that selects no count measures nothing"
        );
        // COUNT-ONLY is what makes it affordable: MEASURED 2026-09-11, 10
        // count-only aliases over dense day-slices answered in 1.4-1.5s
        // where the same 10 carrying 50 nodes each straddled the ~11s
        // deadline and failed.
        assert!(
            !doc.contains("nodes"),
            "nodes would put the series under the node deadline this \
             document is sized to avoid"
        );
    }

    /// Alias indices are ABSOLUTE across the load, not per chunk.
    /// Chunks complete out of order and merge into one map, so a
    /// per-chunk `s0` from chunk two would overwrite chunk one's and
    /// silently corrupt the totals -- the same failure
    /// `query.rs:667-678` guards for the history series.
    #[test]
    fn chunk_alias_indices_are_absolute() {
        let doc = probe_query(&q(), &slices(3), 10);
        assert!(doc.contains("s10: search"));
        assert!(doc.contains("s12: search"));
        assert!(!doc.contains("s0: search"));
    }

    /// A detail slice must carry `issueCount` ALONGSIDE its nodes, or a
    /// slice truncated at the 1,000 cap is indistinguishable from a
    /// complete one -- which is exactly the silent truncation #802 and
    /// #790 shipped.
    #[test]
    fn a_detail_slice_reports_its_true_total_beside_its_nodes() {
        let doc = slice_detail_query(&q(), &slices(1), 0, 100);
        let body = doc.split_once("s0: search").expect("the slice alias").1;
        let before_nodes = body.split_once("nodes").expect("slice nodes").0;
        assert!(
            before_nodes.contains("issueCount"),
            "without the true total, a truncated slice looks complete"
        );
    }

    /// Every field on this document must be free, and "free" turned out
    /// to be about the ARGUMENT, not the field.
    ///
    /// # What this test used to assert, and what measuring changed
    ///
    /// It forbade `reviews` outright, on #823's premise that "a connection
    /// is priced per search". That premise is too broad, which #826's
    /// measurement established -- the guard did its job: it forced the
    /// measurement before the field went in. Live API, `gh api graphql`,
    /// 2026-09-11, `org:FNX-Labs`, the same document this function builds:
    ///
    /// | Nested field | 3 searches | 6 searches | 15 searches |
    /// |---|---|---|---|
    /// | scalars only | 1 | 1 | 1 |
    /// | `reviews { totalCount }` | 1 | 1 | 1 |
    /// | `reviews(first: 1) { totalCount }` | 1 | **2** | **2** |
    /// | `labels { totalCount }` | 1 | 1 | - |
    /// | `labels(first: 10) { nodes { name } }` | 1 | **2** | - |
    ///
    /// The SAME field is free without `first:` and priced with it, for both
    /// `reviews` and `labels`. That reconciles with `poll.rs:1503-1580`
    /// rather than contradicting it: every connection on that test's cost
    /// list is a paged one, so its figures were right about the query it
    /// measured.
    ///
    /// So the rule this guards is now: a connection may be read for
    /// `totalCount`, and may NOT take a `first:` argument. `board.rs`'s
    /// module docs carry the full table.
    #[test]
    fn the_detail_slice_carries_only_unpriced_fields() {
        let doc = slice_detail_query(&q(), &slices(1), 0, 100);
        for scalar in ["additions", "deletions", "changedFiles"] {
            assert!(doc.contains(scalar), "{scalar} is a free scalar and wanted");
        }
        // The reviewer leaderboard #826 asked for, in the spelling that
        // measured free.
        assert!(
            doc.contains("reviews { totalCount }"),
            "the reviewer board needs a review count per PR"
        );
        // A PAGED nested connection is the priced shape. Checked as
        // `name(` so the argument is what trips it -- which is the thing
        // that was actually measured, and is invisible in review because
        // both spellings read as "one more field".
        //
        // The outer `search(` and the document's own `first:` are not
        // nested connections and are excluded by checking only the node
        // selection, which is where a per-PR field would be added.
        let nodes = doc
            .split_once("... on PullRequest {")
            .expect("the node selection")
            .1;
        for connection in [
            "reviews(",
            "comments(",
            "labels(",
            "reviewThreads(",
            "commits(",
        ] {
            assert!(
                !nodes.contains(connection),
                "{connection} PAGES a nested connection, which measured 2 points \
                 from 6 searches up -- read it for totalCount instead, or \
                 measure the live cost first"
            );
        }
    }

    /// The connection path takes no date range, because GitHub's
    /// `pullRequests` connection does not offer one. Pinned so a reader
    /// does not "fix" it by inventing a `filterBy` argument that the
    /// schema rejects.
    #[test]
    fn the_connection_query_orders_by_update_time_and_filters_client_side() {
        assert!(REPO_CONNECTION_QUERY.contains("orderBy: { field: UPDATED_AT"));
        assert!(REPO_CONNECTION_QUERY.contains("totalCount"));
        assert!(REPO_CONNECTION_QUERY.contains("pageInfo { hasNextPage endCursor }"));
        assert!(
            !REPO_CONNECTION_QUERY.contains("merged:"),
            "the connection takes no date qualifier; the filter is client-side"
        );
    }

    /// The reviewer document counts reviews GIVEN, and must not carry an
    /// author qualifier.
    ///
    /// This is the test for the thing that made #829 refuse to ship the
    /// requested title: `reviews { totalCount }` counts reviews RECEIVED, so
    /// the only honest "top reviewers" board needs `reviewed-by:`. And the
    /// author must be GONE rather than alongside it -- `author:X
    /// reviewed-by:Y` is a legal search meaning "X's pull requests that Y
    /// reviewed", a third question whose wrongness no figure on screen could
    /// reveal.
    ///
    /// Asserted on the WHOLE string rather than on substrings, for
    /// `a_named_subject_replaces_the_viewer_entirely`'s reason: a
    /// `contains("reviewed-by:octocat")` check would pass happily while a
    /// stray `author:@me` narrowed the board to the viewer's own pull
    /// requests.
    #[test]
    fn the_reviewer_document_counts_reviews_given_by_anyone() {
        // A query carrying a SUBJECT, deliberately: that is the realistic
        // mistake, since `StatsQuery` is usually built with one.
        let authored = StatsQuery::new(
            Some(Subject::Viewer),
            Scope::Org("FNX-Labs".into()),
            Measure::Merged,
        );
        let doc = reviewer_query(
            &authored,
            &["octocat".to_string(), "hubot".to_string()],
            &Slice::new("2026-08-12", "2026-09-10"),
            0,
        );
        assert!(
            doc.contains(
                "\"is:pr is:merged reviewed-by:octocat org:FNX-Labs merged:2026-08-12..2026-09-10\""
            ),
            "the reviewer search must drop the author entirely: {doc}"
        );
        assert!(
            !doc.contains("author:"),
            "an author qualifier alongside reviewed-by asks a third question: {doc}"
        );
        // One alias per login, with ABSOLUTE indices so chunks merging into
        // one map cannot attribute one colleague's count to another.
        assert!(doc.contains("v0: search("));
        assert!(doc.contains("v1: search("));
        assert_eq!(doc.matches("search(").count(), 2);
    }

    /// The reviewer document is COUNT-ONLY and unpaged, which is what makes
    /// it cost 1 point.
    ///
    /// MEASURED live 2026-09-11 on `org:FNX-Labs`: cost 1 at 4, 10 and 36
    /// aliases (0.84-1.04s, 1.26-1.50s, 3.62-4.15s). A `first:` argument is
    /// what GitHub prices, so adding one to a connection read only for a
    /// count would buy nothing and could cost a point per search -- and a
    /// `nodes` selection would put this document under the ~11s node deadline
    /// that `board.rs`'s table shows kills 10 aliases at a 50-node page.
    #[test]
    fn the_reviewer_document_is_count_only_and_unpaged() {
        let doc = reviewer_query(
            &q(),
            &["octocat".to_string()],
            &Slice::new("2026-08-12", "2026-09-10"),
            0,
        );
        assert!(doc.contains("{ issueCount }"));
        assert!(
            !doc.contains("nodes"),
            "nodes would put this document under the node deadline"
        );
        assert!(
            !doc.contains("first:"),
            "a `first:` argument is the priced shape and buys a count nothing"
        );
        // And the cost is READ rather than assumed, on every request.
        assert!(doc.contains("rateLimit { cost remaining resetAt }"));
    }

    /// A reviewer login cannot break out of the string literal either.
    ///
    /// The same guard `a_subject_cannot_break_out_of_the_string_literal`
    /// gives, on the second path that now takes a login from the sidebar --
    /// which is whatever GitHub returned.
    #[test]
    fn a_reviewer_login_cannot_break_out_of_the_string_literal() {
        let doc = reviewer_query(
            &q(),
            &["a\" evil: \"b".to_string()],
            &Slice::new("2026-08-12", "2026-09-10"),
            0,
        );
        assert!(doc.contains("\\\""), "the quote must be escaped");
        assert_eq!(doc.matches("search(").count(), 1);
        assert_eq!(doc.matches('{').count(), doc.matches('}').count());
    }

    /// EVERY document must be valid GraphQL: balanced braces, one
    /// top-level closing brace, and it closes the document.
    ///
    /// Iterates [`every_document`], which is what brought `series_query` in
    /// -- it was absent from this test and from the metering one, the only
    /// document in the module missing from both (#847).
    ///
    /// `REPO_CONNECTION_QUERY` is skipped: it is a `const` with a leading
    /// newline rather than a built string, so its braces are balanced but
    /// the "one bare closing brace on the last line" shape does not apply.
    /// Its own guard is
    /// `the_connection_query_orders_by_update_time_and_filters_client_side`.
    #[test]
    fn documents_are_balanced() {
        for (name, doc) in every_document() {
            if name == "REPO_CONNECTION_QUERY" {
                assert_eq!(doc.matches('{').count(), doc.matches('}').count());
                continue;
            }
            assert_eq!(
                doc.matches('{').count(),
                doc.matches('}').count(),
                "unbalanced braces in {name}: {doc}"
            );
            let bare: Vec<usize> = doc
                .lines()
                .enumerate()
                .filter(|(_, l)| l.trim() == "}")
                .map(|(i, _)| i)
                .collect();
            assert_eq!(bare.len(), 1, "exactly one top-level closing brace");
            // `lines()` on a string ending in "}\n" yields the brace as
            // the LAST line -- the trailing newline is a terminator, not
            // an empty line. Asserted against the real count rather than
            // a guessed offset.
            assert_eq!(bare[0], doc.lines().count() - 1, "and it closes the query");
        }
    }

    /// The subject is a PARAMETER now (#824 item 7), and #825 will hand
    /// over whatever GitHub returned for a login. A value carrying a
    /// quote must not be able to break out of the string literal.
    #[test]
    fn a_subject_cannot_break_out_of_the_string_literal() {
        let hostile = StatsQuery::new(
            Some(Subject::Login("a\" evil: \"b".into())),
            Scope::All,
            Measure::Merged,
        );
        let doc = probe_query(&hostile, &slices(1), 0);
        assert!(doc.contains("\\\""), "the quote must be escaped");
        // Still exactly one search: the injected text did not become a
        // second alias or a second argument.
        assert_eq!(doc.matches("search(").count(), 1);
        assert_eq!(doc.matches('{').count(), doc.matches('}').count());
    }

    /// A single-repo scope still builds a valid search document -- the
    /// connection is PREFERRED, not mandatory, and a malformed
    /// `owner/name` falls back here rather than failing the load.
    #[test]
    fn a_repo_scope_still_has_a_working_search_path() {
        let r = StatsQuery::new(
            Some(Subject::Viewer),
            Scope::Repo("pktstorm/headstate".into()),
            Measure::Merged,
        );
        let doc = probe_query(&r, &slices(1), 0);
        assert!(doc.contains("repo:pktstorm/headstate"));
    }
}
