//! The stats layer's GraphQL documents. Reads only, like `query.rs` one
//! level up, and for the same reason: this file stays auditable as pure
//! search and connection lookups.
//!
//! Two shapes, and the difference between them is the whole routing
//! decision of #824 item 5:
//!
//! - [`probe_query`] and [`slice_detail_query`] use `search`, which is
//!   capped at 1,000 retrievable results and is the only way to ask a
//!   question that spans repositories.
//! - [`repo_connection_query`] uses `repository.pullRequests`, a
//!   connection with no such cap, which is both exact and cheaper for a
//!   single-repo scope.

use crate::github::stats::scope::StatsQuery;

/// Searches per aliased document.
///
/// # This is a LATENCY budget, and the ceiling is a DEADLINE, not an
/// alias count
///
/// `query.rs:226-231` records the ceiling as "~44 aliases: 28-36 succeed
/// 5/5, 44-46 fail intermittently, 60 fails outright", and #823 measured
/// a 502 at 60. I re-measured on 2026-09-11 and the alias count is not
/// what the server is refusing. Every figure below is mine, `gh api
/// graphql` against `org:FNX-Labs`, three runs each:
///
/// | Document shape                     | Aliases | Wall clock     | Result  |
/// |------------------------------------|---------|----------------|---------|
/// | `search { issueCount }`            | 10      | 1.78-1.81s     | ok      |
/// | `search { issueCount }`            | 20      | 2.79-3.21s     | ok      |
/// | `search { issueCount }`            | 36      | 4.40-4.74s     | ok      |
/// | `search { issueCount }`            | 60      | 7.54-7.68s     | ok      |
/// | `search { issueCount }`            | 80      | 8.95-10.48s    | ok      |
/// | `search { issueCount }`            | 100     | 10.97-10.99s   | **502** |
/// | `search(first: 100) { nodes {..} }`| 12      | 3.69-5.21s     | ok      |
/// | `search(first: 100) { nodes {..} }`| 24      | 6.30-7.15s     | ok      |
/// | `search(first: 100) { nodes {..} }`| 36      | 9.22-10.84s    | ok      |
/// | `search(first: 100) { nodes {..} }`| 48      | 10.94s         | **502** |
///
/// The node-heavy document fails at 48 aliases where the count-only one
/// succeeds at 80, so the alias count cannot be the limit. What every
/// failure has in common is the CLOCK: all five 502s landed at
/// 10.94-10.99s, and nothing that answered inside ~10.8s ever failed.
/// It is a server-side deadline of roughly 11 seconds, and alias count
/// matters only because serial evaluation is what drives elapsed time
/// toward it. (The nginx 502 body confirms a gateway timeout rather than
/// a GraphQL objection -- which is also why it arrives as
/// `ClientError::NotJson`, see `client.rs:94-120`.)
///
/// # And the ranges above were SPARSE
///
/// Every row above probes ranges holding a handful of PRs each. Against
/// DENSE ranges -- three month-slices of `org:FNX-Labs` holding 416 / 581
/// / 79 merged PRs -- the document generated by [`slice_detail_query`]
/// itself measured:
///
/// | Aliases x page | Wall clock       | Result      |
/// |----------------|------------------|-------------|
/// | 3 x 100        | 11.0s, then 8.1s | **502**, ok |
/// | 3 x 50         | 3.42-3.68s       | ok 2/2      |
/// | 1 x 100        | 0.52s            | ok 2/2      |
///
/// THREE aliases straddle the deadline when the pages are actually full.
/// So the real driver is the number of NODES MATERIALISED, and alias
/// count is only a proxy for it -- which is why the page size, not the
/// alias count, is the first thing `fetch::degrade` sheds, and why
/// `fetch::SLICE_PAGE_FULL` defaults to 50 rather than 100.
///
/// This REINFORCES the epic's correction rather than undoing it: chunk
/// small and parallelise. It changes why, twice. A chunk size picked as a
/// fraction of an alias ceiling would be safe only for the document shape
/// AND the data density it was measured on -- 48 aliases looked like
/// ample headroom under a 60-alias ceiling, and 36 looked safe until the
/// ranges held real data.
///
/// 10 is sized against the deadline at the default 50-node page: 3
/// aliases x 50 measured 3.42-3.68s on the densest slices in this
/// account, so 10 has room even if every slice is full. It also matches
/// `query::HISTORY_CHUNK_DAYS`'s effective 10 aliases per chunk, which is
/// already measured-and-shipped at 2.36-2.8s, and keeps the existing
/// `<= 40` CI assertion (`query.rs:647-665`) comfortably satisfied.
pub const ALIAS_CHUNK: usize = 10;

/// The upper bound any chunk must respect, asserted in CI.
///
/// Expressed as an alias count because that is what a reviewer editing a
/// chunk size can check, but derived from the deadline above: 40 aliases
/// is ~5s on the count-only shape and ~11s on the node-heavy one, so it
/// is the point past which the expensive document stops being safe. The
/// existing test at `query.rs:647-665` asserts the same number for the
/// history chunks; keeping one figure means the two cannot drift into
/// disagreeing about what "safe" is.
pub const ALIAS_CEILING: usize = 40;

/// One date range to probe or fetch.
///
/// `from` and `to` are inclusive `YYYY-MM-DD`, GitHub's own range
/// grammar and the format `query::period_ranges` already produces.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Slice {
    pub from: String,
    pub to: String,
}

impl Slice {
    pub fn new(from: impl Into<String>, to: impl Into<String>) -> Self {
        Self {
            from: from.into(),
            to: to.into(),
        }
    }
}

/// Alias for the slice at `index`. `s0`, `s1`, ...
///
/// Indices are ABSOLUTE across a whole load, never per chunk, for the
/// reason `query.rs:667-678` records: chunks complete out of order and
/// merge into one map, so a per-chunk index would have chunk two's `s0`
/// silently overwrite chunk one's.
pub fn slice_alias(index: usize) -> String {
    format!("s{index}")
}

/// `issueCount` for each slice, and nothing else.
///
/// This is the probe that drives the slicing in `slice.rs`. No `nodes`,
/// so none of the per-PR fields are resolved at all -- the same
/// reasoning `query::COUNT_QUERY` gives for existing.
///
/// MEASURED 2026-09-11: cost 1 for the whole document at 36, 60 and 80
/// aliases. `rateLimit` is selected so that cost is READ rather than
/// assumed, which is #824 item 1 -- and so the assumption above is
/// checked at runtime on every probe rather than only on the day I
/// measured it.
pub fn probe_query(q: &StatsQuery, slices: &[Slice], first_index: usize) -> String {
    let mut doc = String::from("query {\n  rateLimit { cost remaining resetAt }\n");
    for (i, s) in slices.iter().enumerate() {
        let alias = slice_alias(first_index + i);
        let search = q.search_query(&s.from, &s.to);
        doc.push_str(&format!(
            "  {alias}: search(query: {}, type: ISSUE) {{ issueCount }}\n",
            graphql_string(&search)
        ));
    }
    doc.push_str("}\n");
    doc
}

/// The per-PR detail a leaderboard needs, for each slice.
///
/// `issueCount` rides along on every alias so a slice that is ALREADY
/// over the 1,000 cap is detectable from the same response that returned
/// its nodes -- the count is the true total and the node list is what was
/// retrievable. Without it, a truncated slice and a complete one look
/// identical, which is the silent-truncation shape #802 and #790 both
/// shipped.
///
/// `additions`, `deletions` and `changedFiles` are SCALARS and cost
/// nothing extra. MEASURED 2026-09-11: 12 aliases x 100 nodes carrying
/// all three plus `author { login }` cost **1 point** in 3.69-5.21s.
/// `reviews { totalCount }` is deliberately NOT here: it is a connection
/// and is priced per search (`poll.rs:1503-1580`), so adding it would
/// multiply the cost of this document by its alias count. #826 can add it
/// behind its own measurement if a reviewer leaderboard needs it.
pub fn slice_detail_query(
    q: &StatsQuery,
    slices: &[Slice],
    first_index: usize,
    first: u32,
) -> String {
    let mut doc = String::from("query {\n  rateLimit { cost remaining resetAt }\n");
    for (i, s) in slices.iter().enumerate() {
        let alias = slice_alias(first_index + i);
        let search = q.search_query(&s.from, &s.to);
        doc.push_str(&format!(
            // The alias's own closing brace is INDENTED and kept off a
            // line of its own. A bare "}" on its own line is
            // indistinguishable from the document's top-level closing
            // brace, which is what `documents_are_balanced` checks for --
            // and that check is worth keeping sharp, because an extra or
            // missing top-level brace is a whole-document syntax error
            // that no mapper test would catch.
            "  {alias}: search(query: {}, type: ISSUE, first: {first}) {{\n\
             \x20   issueCount\n\
             \x20   nodes {{ ... on PullRequest {{ author {{ login }} createdAt mergedAt additions deletions changedFiles }} }} }}\n",
            graphql_string(&search)
        ));
    }
    doc.push_str("}\n");
    doc
}

/// A single repository's pull requests, through the CONNECTION.
///
/// The uncapped path, and the reason `Scope::needs_search` exists.
/// VERIFIED live 2026-09-11: `pktstorm/headstate` reports 337 merged
/// pull requests at cost 1, with no 1,000-result ceiling anywhere in the
/// connection -- where the same question asked through `search` on a
/// busy scope silently stops at 1,000 (`is:pr org:FNX-Labs` reports
/// 1,822 and offset 1000 returns `[]`).
///
/// `totalCount` is the connection's own exact total, so a caller can say
/// how much of it this page holds. Date filtering is NOT available on
/// this connection -- it takes `states`, `orderBy` and a cursor, but no
/// date range -- so the caller filters `createdAt`/`mergedAt` itself
/// after ordering by update time. That is stated here because it is the
/// one place the connection is WEAKER than search, and a reader comparing
/// the two needs to know the cost is a client-side filter rather than a
/// missing feature.
pub const REPO_CONNECTION_QUERY: &str = r#"
query($owner: String!, $name: String!, $first: Int!, $after: String) {
  rateLimit { cost remaining resetAt }
  repository(owner: $owner, name: $name) {
    pullRequests(first: $first, after: $after, states: MERGED, orderBy: { field: UPDATED_AT, direction: DESC }) {
      totalCount
      pageInfo { hasNextPage endCursor }
      nodes {
        number
        author { login }
        createdAt
        mergedAt
        additions
        deletions
        changedFiles
      }
    }
  }
}"#;

/// A Rust string as a GraphQL string literal.
///
/// The searches here are built from logins and repository names, which
/// GitHub allows to contain `-`, `.` and `_` but not a quote -- so this
/// cannot currently be reached by a hostile value. It escapes anyway,
/// because the subject is a parameter now (#824 item 7) and the next
/// caller to add is a sidebar (#825) handing over whatever GitHub
/// returned. An injected `"` would not be a security hole so much as a
/// query that fails in a way nobody could read; either way the fix
/// belongs in the one function that builds the literal, not in every
/// caller remembering.
fn graphql_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::github::stats::scope::{Measure, Scope, StatsQuery, Subject};

    fn q() -> StatsQuery {
        StatsQuery::new(
            Some(Subject::Login("octocat".into())),
            Scope::Org("FNX-Labs".into()),
            Measure::Merged,
        )
    }

    fn slices(n: usize) -> Vec<Slice> {
        (0..n)
            .map(|i| {
                Slice::new(
                    format!("2026-0{}-01", i % 9 + 1),
                    format!("2026-0{}-28", i % 9 + 1),
                )
            })
            .collect()
    }

    /// The chunk size must stay under the ceiling the history chunks
    /// already enforce (`query.rs:647-665` asserts `<= 40`), and this
    /// layer's documents are the EXPENSIVE shape -- 48 node-heavy
    /// aliases 502'd at 10.94s in my measurements, where 80 count-only
    /// aliases succeeded. A chunk sized against the cheap shape is not
    /// safe for this one.
    #[test]
    fn a_chunk_stays_well_under_the_deadline() {
        // `const` blocks: both are compile-time constants, so these fail
        // the BUILD rather than a test run.
        const {
            assert!(ALIAS_CHUNK <= ALIAS_CEILING, "chunk exceeds the ceiling");
            // Measured: 36 node-heavy aliases took 9.22-10.84s against a
            // ~11s deadline, so the ceiling cannot be raised past 40
            // without re-measuring the expensive document.
            assert!(ALIAS_CEILING <= 40, "re-measure before raising the ceiling");
        }
        let doc = probe_query(&q(), &slices(ALIAS_CHUNK), 0);
        assert_eq!(doc.matches("search(").count(), ALIAS_CHUNK);
        assert!(doc.matches("search(").count() <= ALIAS_CEILING);
    }

    /// The same ceiling the history chunks use, so the two cannot drift
    /// into disagreeing about what "safe" means.
    #[test]
    fn the_ceiling_matches_the_history_chunk_assertion() {
        let src = include_str!("../query.rs");
        assert!(
            src.contains("count() <= 40"),
            "query.rs no longer asserts a 40-alias ceiling; ALIAS_CEILING must move with it"
        );
    }

    /// Every document in this file selects `rateLimit`, so its cost is
    /// readable. A query that forgot it would have its spend counted as
    /// `unmetered` rather than guessed -- honest, but it would make the
    /// reported total a floor for no reason.
    #[test]
    fn every_document_meters_itself() {
        assert!(probe_query(&q(), &slices(2), 0).contains("rateLimit { cost remaining resetAt }"));
        assert!(slice_detail_query(&q(), &slices(2), 0, 100)
            .contains("rateLimit { cost remaining resetAt }"));
        assert!(REPO_CONNECTION_QUERY.contains("rateLimit { cost remaining resetAt }"));
    }

    /// Alias indices are ABSOLUTE across the load, not per chunk.
    /// Chunks complete out of order and merge into one map, so a
    /// per-chunk `s0` from chunk two would overwrite chunk one's and
    /// silently corrupt the totals -- the same failure
    /// `query.rs:667-678` guards for the history series.
    #[test]
    fn chunk_alias_indices_are_absolute() {
        let doc = probe_query(&q(), &slices(3), 10);
        assert!(doc.contains("s10: search"));
        assert!(doc.contains("s12: search"));
        assert!(!doc.contains("s0: search"));
    }

    /// A detail slice must carry `issueCount` ALONGSIDE its nodes, or a
    /// slice truncated at the 1,000 cap is indistinguishable from a
    /// complete one -- which is exactly the silent truncation #802 and
    /// #790 shipped.
    #[test]
    fn a_detail_slice_reports_its_true_total_beside_its_nodes() {
        let doc = slice_detail_query(&q(), &slices(1), 0, 100);
        let body = doc.split_once("s0: search").expect("the slice alias").1;
        let before_nodes = body.split_once("nodes").expect("slice nodes").0;
        assert!(
            before_nodes.contains("issueCount"),
            "without the true total, a truncated slice looks complete"
        );
    }

    /// `reviews { totalCount }` is a CONNECTION and priced per search
    /// (`poll.rs:1503-1580`), so it would multiply this document's cost
    /// by its alias count. The scalars are free. Guarded because the
    /// difference is invisible in review: both read as "one more field".
    #[test]
    fn the_detail_slice_carries_only_free_scalars() {
        let doc = slice_detail_query(&q(), &slices(1), 0, 100);
        for scalar in ["additions", "deletions", "changedFiles"] {
            assert!(doc.contains(scalar), "{scalar} is a free scalar and wanted");
        }
        for connection in ["reviews", "comments", "labels", "reviewThreads", "commits"] {
            assert!(
                !doc.contains(connection),
                "{connection} is a connection, priced per search -- \
                 measure the live cost before adding it"
            );
        }
    }

    /// The connection path takes no date range, because GitHub's
    /// `pullRequests` connection does not offer one. Pinned so a reader
    /// does not "fix" it by inventing a `filterBy` argument that the
    /// schema rejects.
    #[test]
    fn the_connection_query_orders_by_update_time_and_filters_client_side() {
        assert!(REPO_CONNECTION_QUERY.contains("orderBy: { field: UPDATED_AT"));
        assert!(REPO_CONNECTION_QUERY.contains("totalCount"));
        assert!(REPO_CONNECTION_QUERY.contains("pageInfo { hasNextPage endCursor }"));
        assert!(
            !REPO_CONNECTION_QUERY.contains("merged:"),
            "the connection takes no date qualifier; the filter is client-side"
        );
    }

    /// Both documents must be valid GraphQL: balanced braces, one
    /// top-level closing brace, and it closes the document.
    #[test]
    fn documents_are_balanced() {
        for doc in [
            probe_query(&q(), &slices(3), 0),
            slice_detail_query(&q(), &slices(3), 0, 100),
        ] {
            assert_eq!(
                doc.matches('{').count(),
                doc.matches('}').count(),
                "unbalanced braces in: {doc}"
            );
            let bare: Vec<usize> = doc
                .lines()
                .enumerate()
                .filter(|(_, l)| l.trim() == "}")
                .map(|(i, _)| i)
                .collect();
            assert_eq!(bare.len(), 1, "exactly one top-level closing brace");
            // `lines()` on a string ending in "}\n" yields the brace as
            // the LAST line -- the trailing newline is a terminator, not
            // an empty line. Asserted against the real count rather than
            // a guessed offset.
            assert_eq!(bare[0], doc.lines().count() - 1, "and it closes the query");
        }
    }

    /// The subject is a PARAMETER now (#824 item 7), and #825 will hand
    /// over whatever GitHub returned for a login. A value carrying a
    /// quote must not be able to break out of the string literal.
    #[test]
    fn a_subject_cannot_break_out_of_the_string_literal() {
        let hostile = StatsQuery::new(
            Some(Subject::Login("a\" evil: \"b".into())),
            Scope::All,
            Measure::Merged,
        );
        let doc = probe_query(&hostile, &slices(1), 0);
        assert!(doc.contains("\\\""), "the quote must be escaped");
        // Still exactly one search: the injected text did not become a
        // second alias or a second argument.
        assert_eq!(doc.matches("search(").count(), 1);
        assert_eq!(doc.matches('{').count(), doc.matches('}').count());
    }

    /// A single-repo scope still builds a valid search document -- the
    /// connection is PREFERRED, not mandatory, and a malformed
    /// `owner/name` falls back here rather than failing the load.
    #[test]
    fn a_repo_scope_still_has_a_working_search_path() {
        let r = StatsQuery::new(
            Some(Subject::Viewer),
            Scope::Repo("pktstorm/headstate".into()),
            Measure::Merged,
        );
        let doc = probe_query(&r, &slices(1), 0);
        assert!(doc.contains("repo:pktstorm/headstate"));
    }
}
