//! Standard Tauri plugin build script. `COMMANDS` names the native
//! commands so the permission files exist in the shape Tauri expects;
//! nothing in the webview is ever granted them, because every call
//! into this plugin comes from Rust (`run_mobile_plugin`), which does
//! not pass through the ACL. The frontend cannot start or complete a
//! background window, nor take the Wi-Fi multicast lock.

const COMMANDS: &[&str] = &[
    "register",
    "complete",
    // The Android Wi-Fi multicast lock (#610). Android-only in effect:
    // the iOS side implements no such commands, and Rust never calls
    // them there because `multicast::install` is Android-only.
    //
    // snake_case HERE and camelCase on the wire, which is not a typo:
    // this list names ACL permissions (it generates
    // `permissions/autogenerated/commands/*.toml`), while what Rust
    // passes to `run_mobile_plugin` is the Kotlin `@Command` method
    // name. `headstate-keys` splits the same way -- `store_session`
    // here, `storeSession` in its `wire::cmd`.
    "acquire_multicast",
    "release_multicast",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS)
        .android_path("android")
        .ios_path("ios")
        .build();
}
